"use strict";

var OPUS_RAW_BUFFER_SIZE = 100*1024;
var OPUS_FETCH_BUFFER_LIMIT = 100*1024;
var OPUS_DECODING_SOUND_BUFFER_DURATION = 0.5

var INJECTED_SOUND_DURATION = 0.5
var INJECTED_SOUND_REFRESH_PERIOD_MS = 50

var VOCODER_BUFFER_SIZE = 4096;
var VOCODER_FRAME_SIZE  = 2048;

